language: csharp
solution: UFO.sln
script:
  # Build solution
  - xbuild DALCommon/DALCommon.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DALCommonTest/DALCommonTest.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DALMySql/DALMySql.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DALMySqlTest/DALMySqlTest.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DALTestClient/DALTestClient.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild Database/Database.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DomainClasses/DomainClasses.csproj /p:TargetFrameworkVersion="v4.5"
  - xbuild DomainClassesTest/DomainClassesTest.csproj /p:TargetFrameworkVersion="v4.5"

  # Create DB
  - mysql -u travis < DB/DDL.sql

  # Run Unit Tests
  - mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DALCommonTest/bin/Debug/DALCommonTest.dll
  - mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DomainClassesTest/bin/Debug/UFO.Test.DomainClasses.dll
  - mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DALMySqlTest/bin/Debug/DALIndependentTest.dll
